name: 03 - Workflow Runners v1

on:
  workflow_dispatch:

jobs:
  ubuntu-echo:
    runs-on: sh-aw
    steps:
      - name: Show OS
        shell: bash
        run: |
          echo "This job is running on an Ubuntu runner."
          echo "$RUNNER_OS"
          touuch testfile.txt

  windows-echo:
    runs-on: sh-aw
    steps:
      - name: Show OS
        shell: bash
        run: |
          echo "This job is running on a Windows runner."
          echo "${{ runner.os }}"

  mac-echo:
    runs-on: sh-aw
    steps:
      - name: Show OS
        shell: bash
        run: |
          echo "This job is running on a MacOS runner."
          echo "$RUNNER_OS"